name: Create-Release-Version

on:
  workflow_dispatch: # 手动触发
    inputs:
      version:
        description: '版本号 (例如 v1.0.0)'
        required: true
        default: 'v1.0.0'
  push:
    tags:
      - 'v*' # 当推送了一个以 "v" 开头的标签时自动触发

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout Code
        uses: actions/checkout@v3

      # 创建或更新发布版本
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version || github.ref_name }}
          name: ${{ github.event.inputs.version || github.ref_name }}
          body: |
            ### Release Information
            - 自动生成的版本号: ${{ github.event.inputs.version || github.ref_name }}
            - 发布时间: ${{ github.run_start_time }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 将版本号保存为 artifact
      - name: Save Version Number
        run: echo "${{ github.event.inputs.version || github.ref_name }}" > version.txt

      # 上传版本号文件
      - name: Upload Version Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-version
          path: version.txt